# Simple ccache locator

unset(CCACHE_EXECUTABLE CACHE)

find_file(CCACHE_EXECUTABLE ccache)

if(NOT CCACHE_EXECUTABLE)
  SET(CCACHE_FOUND "NO")
else(NOT CCACHE_EXECUTABLE)
  SET(CCACHE_FOUND "YES")
endif(NOT CCACHE_EXECUTABLE)